### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by XProger** [XProger/RealTournament#1]
- [x] Инициализация окна и контекста
- [x] Вывод треугольника
- [x] Загрузка текстур (TARGA)
- [x] Вершинный буфер
- [x] Шейдера
- [x] Ввод с клавиатуры и мыши
- [x] Камера
- [x] Blender, модель уровня, экспорт
- [x] Вывод уровня на экран
- [x] Игрок, коллизии игрока с уровнем
- [ ] Триггеры, кнопки, лифты
- [x] Враги, модели врагов (боксы)
- [x] Blender, оружие (пистолет), стрельба
- [x] Звук (wav)
- [x] HUD
- [ ] Сетевой код
- [ ] Меню
- [ ] Оружие и эффекты
- [ ] AI врагов
